name: build

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
      - name: Install deps
        run: poetry install
      - name: Run Mypy
        run: make mypy
      - name: Run Pytype
        if: ${{ matrix.python-version != 3.8 && matrix.os == 'ubuntu-latest' }}
        run: make pytype
      - name: Run tests
        run: make test

  publish:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs: ci
    env:
      PYPI_API_KEY: ${{ secrets.PYPI_API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
      - name: Install deps
        run: poetry install
      - name: Build
        run: poetry build
      - name: Publish
        run: poetry publish -u __token__ -p $PYPI_API_KEY
